auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.22.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.22.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.22.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.22.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.21.5
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.21.5
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.21.5
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.21.5
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.20.10
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.20.10
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.20.10
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.20.10
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-apiserver:v1.19.9
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controller-manager:v1.19.9
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-proxy:v1.19.9
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-scheduler:v1.19.9
  registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.5
  registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/coredns:1.8.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/cni:v3.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-controllers:v3.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/node:v3.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/pod2daemon-flexvol:v3.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/typha:v3.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/flannel:v0.12.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/provisioner-localpv:2.10.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/linux-utils:2.10.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:2.3
  registry.cn-beijing.aliyuncs.com/kubesphereio/nfs-subdir-external-provisioner:v4.0.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-dns-node-cache:1.15.12
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-installer:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-apiserver:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-console:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-controller-manager:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.21.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kubectl:v1.20.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kubefed:v0.8.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/tower:v0.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/minio:RELEASE.2019-08-07T01-59-21Z
  registry.cn-beijing.aliyuncs.com/kubesphereio/mc:RELEASE.2019-08-07T23-14-43Z
  registry.cn-beijing.aliyuncs.com/kubesphereio/snapshot-controller:v4.0.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/nginx-ingress-controller:v0.48.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/defaultbackend-amd64:1.4
  registry.cn-beijing.aliyuncs.com/kubesphereio/metrics-server:v0.4.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/redis:5.0.14-alpine
  registry.cn-beijing.aliyuncs.com/kubesphereio/haproxy:2.0.25-alpine
  registry.cn-beijing.aliyuncs.com/kubesphereio/alpine:3.14
  registry.cn-beijing.aliyuncs.com/kubesphereio/openldap:1.3.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/netshoot:v1.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/cloudcore:v1.7.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/edge-watcher:v0.1.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/edge-watcher-agent:v0.1.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/gatekeeper:v3.5.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/openpitrix-jobs:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/devops-apiserver:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/devops-controller:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/devops-tools:v3.2.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/ks-jenkins:v3.2.0-2.249.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/jnlp-slave:3.27-1
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-base:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-nodejs:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-maven:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-python:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-go:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-go:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-base:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-nodejs:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-maven:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-python:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-go:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/builder-go:v3.2.0-podman
  registry.cn-beijing.aliyuncs.com/kubesphereio/s2ioperator:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/s2irun:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/s2i-binary:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/tomcat85-java11-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/tomcat85-java11-runtime:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/tomcat85-java8-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/tomcat85-java8-runtime:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/java-11-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/java-8-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/java-8-runtime:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/java-11-runtime:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/nodejs-8-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/nodejs-6-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/nodejs-4-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/python-36-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/python-35-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/python-34-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/python-27-centos7:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/configmap-reload:v0.3.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/prometheus:v2.26.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/prometheus-config-reloader:v0.43.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/prometheus-operator:v0.43.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-rbac-proxy:v0.8.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-state-metrics:v1.9.7
  registry.cn-beijing.aliyuncs.com/kubesphereio/node-exporter:v0.18.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/k8s-prometheus-adapter-amd64:v0.6.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/alertmanager:v0.21.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/thanos:v0.18.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/grafana:7.4.3
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-rbac-proxy:v0.8.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/notification-manager-operator:v1.4.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/notification-manager:v1.4.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/notification-tenant-sidecar:v3.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/elasticsearch-curator:v5.7.6
  registry.cn-beijing.aliyuncs.com/kubesphereio/elasticsearch-oss:6.7.0-1
  registry.cn-beijing.aliyuncs.com/kubesphereio/fluentbit-operator:v0.11.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/docker:19.03
  registry.cn-beijing.aliyuncs.com/kubesphereio/fluent-bit:v1.8.3
  registry.cn-beijing.aliyuncs.com/kubesphereio/log-sidecar-injector:1.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/filebeat:6.7.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-events-operator:v0.3.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-events-exporter:v0.3.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-events-ruler:v0.3.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-auditing-operator:v0.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/kube-auditing-webhook:v0.2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/pilot:1.11.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/proxyv2:1.11.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-operator:1.27
  registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-agent:1.27
  registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-collector:1.27
  registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-query:1.27
  registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-es-index-cleaner:1.27
  registry.cn-beijing.aliyuncs.com/kubesphereio/kiali-operator:v1.38.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/kiali:v1.38
  registry.cn-beijing.aliyuncs.com/kubesphereio/busybox:1.31.1
  registry.cn-beijing.aliyuncs.com/kubesphereio/nginx:1.14-alpine
  registry.cn-beijing.aliyuncs.com/kubesphereio/wget:1.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/hello:plain-text
  registry.cn-beijing.aliyuncs.com/kubesphereio/wordpress:4.8-apache
  registry.cn-beijing.aliyuncs.com/kubesphereio/hpa-example:latest
  registry.cn-beijing.aliyuncs.com/kubesphereio/java:openjdk-8-jre-alpine
  registry.cn-beijing.aliyuncs.com/kubesphereio/fluentd:v1.4.2-2.0
  registry.cn-beijing.aliyuncs.com/kubesphereio/perl:latest
  registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-productpage-v1:1.16.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-reviews-v1:1.16.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-reviews-v2:1.16.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-details-v1:1.16.2
  registry.cn-beijing.aliyuncs.com/kubesphereio/examples-bookinfo-ratings-v1:1.16.3
  
  
  
